name: Android CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sanity echo (validate workflow engine runs jobs)
      run: |
        echo "Runner: $RUNNER_OS"
        echo "Repo: $GITHUB_REPOSITORY, SHA: $GITHUB_SHA"
